import {useRef,useState,useEffect} from 'react';
import {ArrowUp,Square,Plus,X,Paperclip,ChevronDown} from 'lucide-react';
import type {Attachment,AgentMode} from '../../types';
import type {Preferences} from '../../state/settings';
import {models} from '../../mock/data';
import {t} from '../../i18n';
export function Composer({busy,onSend,onStop,preferences,onChange,draft,setDraft}:{busy:boolean;onSend:(text:string,attachments:Attachment[])=>Promise<boolean|undefined>;onStop:()=>void;preferences:Preferences;onChange:(p:Partial<Preferences>)=>void;draft:string;setDraft:(s:string)=>void}){
 const textarea=useRef<HTMLTextAreaElement>(null),fileRef=useRef<HTMLInputElement>(null);
 const [attachments,setAttachments]=useState<Attachment[]>([]),[notice,setNotice]=useState('');
 useEffect(()=>{const e=textarea.current;if(e){e.style.height='auto';e.style.height=`${Math.min(e.scrollHeight,180)}px`;}},[draft]);
 const submit=async()=>{const content=draft,files=attachments;const accepted=await onSend(content,files);if(accepted){setDraft('');setAttachments([]);textarea.current?.focus();}};
 return <div className="composer-area"><div className="composer">{attachments.length>0&&<div className="attachments">{attachments.map(a=><span key={a.id} className="attachment-chip"><Paperclip size={14}/><span>{a.name}</span><button className="icon-button" aria-label={`Usuń załącznik ${a.name}`} onClick={()=>setAttachments(as=>as.filter(x=>x.id!==a.id))}><X size={14}/></button></span>)}</div>}<textarea ref={textarea} value={draft} onChange={e=>setDraft(e.target.value)} rows={1} placeholder={t.placeholder} aria-label="Treść wiadomości" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(!busy&&(draft.trim()||attachments.length))void submit();}}}/><div className="composer-toolbar"><input type="file" ref={fileRef} hidden onChange={e=>{const file=e.target.files?.[0];if(file){setAttachments(as=>[...as,{id:crypto.randomUUID(),name:file.name,size:file.size,mimeType:file.type,status:'placeholder'}]);setNotice('Załącznik to element demonstracyjny. Plik nie jest odczytywany ani przesyłany.');}e.target.value='';}}/><button className="icon-button" title="Dodaj załącznik — demonstracja" aria-label="Dodaj załącznik" onClick={()=>setNotice('Przesyłanie załączników nie jest jeszcze dostępne.')}><Plus size={20}/></button><div className="select-wrap"><select aria-label="Wybierz model" value={preferences.modelId} onChange={e=>onChange({modelId:e.target.value})}>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><ChevronDown size={12}/></div><span className="toolbar-divider"/><div className="select-wrap"><select aria-label="Tryb agenta" value={preferences.mode} onChange={e=>onChange({mode:e.target.value as AgentMode})}>{Object.entries(t.modes).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><ChevronDown size={12}/></div><span className="toolbar-spacer"/>{busy?<button className="send-button stopping" aria-label={t.stop} title={t.stop} onClick={onStop}><Square size={15} fill="currentColor"/></button>:<button className="send-button" aria-label={t.send} title={t.send} disabled={!draft.trim()&&!attachments.length} onClick={()=>void submit()}><ArrowUp size={20}/></button>}</div></div>{notice&&<div className="composer-notice" role="status">{notice}<button className="icon-button" aria-label="Zamknij informację" onClick={()=>setNotice('')}><X size={13}/></button></div>}<p className="composer-footnote">Odpowiedzi z Osa-jev · receipt nie oznacza weryfikacji APR.<span> Enter — wyślij · Shift + Enter — nowy wiersz</span></p></div>;
}
