import {useState} from 'react';
import {ChevronRight,ShieldCheck,Route,Activity,ArrowUpRight} from 'lucide-react';
import type {Execution,ProofRecord} from '../../types';
import {t} from '../../i18n';
import {Dialog} from '../../components/Dialog';
import {CopyButton} from '../../components/CopyButton';
export function ProofDialog({proof,onClose}:{proof:ProofRecord;onClose:()=>void}){
 return <Dialog title="Receipt wykonania" onClose={onClose}><div className="proof-body"><div className="notice"><ShieldCheck size={18}/><div><strong>Zarejestrowane wykonanie</strong><p>Receipt z backendu. EXECUTION_RECORDED nie oznacza weryfikacji APR.</p></div></div><dl className="receipt"><dt>Status</dt><dd><span className="status-label good">Zarejestrowano</span></dd><dt>Identyfikator potwierdzenia</dt><dd><code>{proof.id}</code><CopyButton text={proof.id} label="Kopiuj identyfikator potwierdzenia"/></dd><dt>Identyfikator wykonania</dt><dd><code>{proof.executionId}</code></dd><dt>Czas</dt><dd>{new Date(proof.timestamp).toLocaleString('pl-PL')}</dd></dl><h3>Rekordy dowodowe</h3>{proof.evidence.map((e,i)=><div className="evidence" key={i}><code>{e.type}</code><p>{e.description}</p><small>Źródło: {e.source}</small></div>)}</div></Dialog>;
}
export function ExecutionDetails({execution,proof,showProof}:{execution:Execution;proof?:ProofRecord;showProof:boolean}){
 const [open,setOpen]=useState(false),[trace,setTrace]=useState(false),[viewProof,setViewProof]=useState(false);
 return <div className="execution"><button className="execution-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><ChevronRight size={14} className={open?'rotated':''}/><Activity size={14}/><span>Wykonanie</span><span className={`status-dot ${execution.status==='failed'?'bad':execution.status==='running'?'working':execution.status==='cancelled'?'warn':'good'}`}/><span>{execution.status==='running'?'W toku':execution.status==='completed'?'Zakończono':execution.status==='cancelled'?'Przerwano':'Błąd'}</span><small>Runtime</small></button>{open&&<div className="execution-content"><p className="muted tiny">Bezpieczne zdarzenia systemowe. Statusy bez dowodu pozostają niepotwierdzone.</p><div className="component-list">{Object.entries(execution.components).map(([name,status])=><div key={name}><span>{name}</span><span className={`status-label ${status==='failed'?'bad':status==='running'?'working':(status==='pending'||status==='unknown')?'muted':'good'}`}>{t.status[status]}</span></div>)}</div><button className="text-button" onClick={()=>setTrace(!trace)} aria-expanded={trace}><Route size={15}/>{t.trace}<ChevronRight size={13} className={trace?'rotated':''}/></button>{trace&&<ol className="trace-list">{execution.steps.map(s=><li key={s.id}><span className={`trace-mark ${s.status==='failed'?'bad':s.status==='running'?'working':''}`}/><div><strong>{s.name}</strong><small>{new Date(s.timestamp).toLocaleTimeString('pl-PL')} · {s.durationMs} ms</small></div><span className="tiny muted">{t.status[s.status]}</span></li>)}</ol>}{showProof&&proof&&<div className="proof-strip"><ShieldCheck size={16}/><div><strong>Receipt · Zarejestrowano</strong><code>{proof.id}</code></div><button className="text-button" onClick={()=>setViewProof(true)}>Zobacz potwierdzenie<ArrowUpRight size={14}/></button></div>}{execution.components.APR==='failed'&&<p className="error-text tiny">Brak potwierdzenia — weryfikacja nie powiodła się.</p>}</div>}{viewProof&&proof&&<ProofDialog proof={proof} onClose={()=>setViewProof(false)}/>}</div>;
}
